import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { Nunito } from 'next/font/google';
import TaskList from '@/components/taskList/TaskList';
import Link from 'next/link';
import { useTaskContext } from '@/components/taskContext/TaskContext';
import image from "../assets/image.png";
import styles from '@/styles/syles.module.css';
import CompletedTasksList from '@/components/completedTasks/CompletedTaskList';
import { Button } from 'react-bootstrap';

const inter = Nunito({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin']
});

const Home: React.FC = () => {
  const { tasks, deleteTask, toggleTask, getCompletedTasks } = useTaskContext();
  const completedTasks = getCompletedTasks();
  
  const handleDeleteTask = (index: number) => {
    deleteTask(index);
  };
  const [currentDate, setCurrentDate] = useState('');
  const [currentDayOfWeek, setCurrentDayOfWeek] = useState('');
  useEffect(() => {
    updateCurrentDateAndDayOfWeek();
  }, []);

  const updateCurrentDateAndDayOfWeek = () => {
    const date = new Date();
    const formattedDate = date.toLocaleDateString('EN', { day: '2-digit', month: 'long', year: 'numeric' });
    setCurrentDate(formattedDate);

    const dayOfWeek = date.toLocaleDateString('EN', { weekday: 'long' });
    setCurrentDayOfWeek(dayOfWeek);
  };

  const totalTasks = tasks.length;
  const totalCompletedTasks = completedTasks.length;

  return (
    <div className={`d-flex flex-column justify-content-center align-items-center ${styles.container}`}>
      <Head>
        <title>Todo-list</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="d-flex align-items-center justify-content-center text-light my-4">
        <div className= {`d-flex flex-column ${styles.top_container}`}>
          <span className={styles.date_day}>{currentDayOfWeek}</span>
          <span className={styles.date}>{currentDate}</span>
        </div>
        <div className="ml-4">
          <Image src={image} alt='' className={styles.image} />
        </div>
      </div>
      <div>
        <h1 className={styles.title_task_list}>Task<br /> List</h1>
        <p className={styles.title_task_finished}> {`${totalCompletedTasks} / ${totalTasks + totalCompletedTasks}`} Task finished</p>
      </div>
      
      <div>
        <CompletedTasksList tasks={completedTasks} />
      </div>
     
      <div>
        <TaskList tasks={tasks} onToggleTask={toggleTask} onDeleteTask={handleDeleteTask} />
      </div>
      
     
      <div className={styles.container_button}>
        <Link href="/addpage">
          <Button className={styles.button_task}>Create Task</Button>
        </Link>
      </div>
    </div>

  );
};

export default Home;
